# Generated by Django 3.2.9 on 2021-11-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
