# Generated by Django 3.2.9 on 2021-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=255, verbose_name='userId')),
                ('type', models.CharField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], max_length=50, verbose_name='type')),
                ('number', models.CharField(max_length=50, verbose_name='number')),
                ('expDate', models.DateField(verbose_name='expDate')),
                ('cv', models.CharField(max_length=3, verbose_name='cv')),
            ],
        ),
    ]
